// Hand-written from the API contract in CLAUDE.md.
// Once the FastAPI backend exists, replace with types generated by `npm run gen:api`.

export type PromptLanguage = "uz" | "ru";

export type Tone = "positive" | "neutral" | "negative";

export type ReportPeriod = "week";

export interface Brand {
  id: string;
  name: string;
  /** Other spellings, Latin and Cyrillic, e.g. "Oq Tabassum", "Ок Табассум". */
  aliases: string[];
  domain: string;
}

/** The paid plans (names in messages/Plans). The free check has no project. */
export type Plan = "start" | "business" | "agency";

/** What the project's plan allows. */
export interface ProjectLimits {
  /**
   * Questions the project may track at once; archived ones don't count. On the agency plan the plan's questions
   * are shared by the agency's brands, and this is what this brand may use.
   */
  prompts: number;
  /** Competitors it may track. */
  competitors: number;
}

export interface Project {
  id: string;
  brand: Brand;
  competitors: Brand[];
  category: string;
  city: string;
  languages: PromptLanguage[];
  /** The brand profile from onboarding: a sentence or two on the business ("" if none). */
  description: string;
  /** What the business offers, as the client wrote it ("Implantlar", "Breketlar"); steers suggested questions. */
  services: string[];
  plan: Plan;
  limits: ProjectLimits;
}

export interface Prompt {
  id: string;
  text: string;
  language: PromptLanguage;
  topic: string;
  /** ISO 8601: when it was added. Its results start with the first run after that. */
  createdAt: string;
  /**
   * ISO 8601: when the client stopped tracking it; null while it is tracked. An archived question isn't
   * asked any more and is left out of the report, keeps its past answers (its own page still shows them),
   * and doesn't count toward the plan's limit. It can be tracked again.
   */
  archivedAt: string | null;
}

export interface ReportMethod {
  engine: string;
  model: string;
  webSearch: boolean;
  /** Answers collected per prompt. */
  samples: number;
  /** ISO 8601 timestamp. */
  collectedAt: string;
}

export interface BrandScore {
  brandId: string;
  /** Answers naming the brand / all answers, 0–1. */
  visibility: number;
  /** Mentions of the brand / mentions of all tracked brands, 0–1. */
  shareOfVoice: number;
  /** Mean position (1 = first) over answers naming the brand; null if never named. */
  avgPosition: number | null;
  /** Mean tone of the brand's mentions, 0–100 (positive 100, neutral 50, negative 0); null if never named. */
  sentiment: number | null;
  /** Change in visibility vs the previous period, e.g. 0.05 = +5 points. */
  trend: number;
}

export interface Mention {
  brandId: string;
  /** 1 = first clinic named in the answer. */
  position: number;
  tone: Tone;
}

export interface Citation {
  url: string;
  domain: string;
}

export interface Answer {
  /** 1-based sample number. */
  sample: number;
  text: string;
  mentions: Mention[];
  citations: Citation[];
}

export interface PromptResult {
  prompt: Prompt;
  answers: Answer[];
}

/**
 * own: the brand's website; competitor: a tracked competitor's website; news: news sites;
 * directory: maps, catalogs and review sites; social: social networks and Telegram channels.
 */
export type SourceType = "own" | "competitor" | "news" | "directory" | "social" | "other";

export interface CitedPage {
  url: string;
  /** How many answers cited this page. */
  count: number;
  /** Tracked brands (ids) the page names, found by reading it; null when it couldn't be read. */
  mentions: string[] | null;
}

export interface Source {
  domain: string;
  type: SourceType;
  /** How many answers cited this domain. */
  count: number;
  /** Whether the project's brand is listed on this source. */
  brandListed: boolean;
  /** The domain's pages the answers cite, most cited first. */
  pages: CitedPage[];
}

export interface WrongFact {
  claim: string;
  correct: string;
  promptId: string;
  /** ISO 8601 timestamp of the run that first found it. */
  foundAt: string;
}

/** One finished run: every tracked brand's scores at that time. */
export interface HistoryPoint {
  /** ISO 8601 timestamp. */
  collectedAt: string;
  scores: Omit<BrandScore, "trend">[];
}

/** A brand the answers name that the project doesn't track: a possible new competitor. */
export interface UntrackedBrand {
  name: string;
  /** How many answers named it. */
  answers: number;
}

/**
 * listing: get onto a site ChatGPT relies on; fact: correct something ChatGPT gets wrong; content: publish
 * a page that answers questions where the brand is missing; technical: a fix on the brand's own website.
 */
export type ActionKind = "listing" | "fact" | "content" | "technical";

/** new: suggested; in_progress: the client took it on; done: the client says it's done; declined: not doing it. */
export type ActionStatus = "new" | "in_progress" | "done" | "declined";

/** Expected effect on visibility, compared with the project's other actions. */
export type ActionImpact = "high" | "medium" | "low";

/** Checks the backend runs on the brand's website. */
export type SiteCheck = "ai_bots_blocked" | "prices_as_images" | "no_business_markup" | "contacts_missing";

/** One check on the brand's website; `passed` false means the problem was found. */
export interface SiteCheckResult {
  check: SiteCheck;
  passed: boolean;
}

interface ActionBase {
  id: string;
  status: ActionStatus;
  impact: ActionImpact;
  /** The questions it should improve, most affected first. */
  promptIds: string[];
  /** ISO 8601: the run that suggested it. */
  createdAt: string;
  /** ISO 8601: when it was marked done; null otherwise. */
  doneAt: string | null;
  /** The how-to steps the client has checked off, by index (0 = first), ascending; a half-done fix shows where it stopped. */
  stepsDone: number[];
  /**
   * Fix → proof: the brand's visibility (0–1) on `promptIds` in the last run before it was done, and
   * in the latest run, `runs` runs later. Null until a run has finished since it was done.
   */
  proof: { before: number; after: number; runs: number } | null;
}

/** A recommended fix, made from the weekly report. Steps are written by the frontend from `kind` and its fields. */
export type Action = ActionBase &
  (
    | {
        kind: "listing";
        domain: string;
        sourceType: SourceType;
        /** Answers citing the site. */
        answers: number;
        /** Tracked competitors named in those answers, most named first. */
        competitorIds: string[];
      }
    | { kind: "fact"; claim: string; correct: string }
    | { kind: "content"; topic: string }
    | { kind: "technical"; check: SiteCheck }
  );

export interface User {
  id: string;
  /** From Telegram; null for accounts made with a phone number. */
  name: string | null;
  /** E.164, e.g. "+998901234567"; null for Telegram-only accounts. */
  phone: string | null;
  telegramUsername: string | null;
}

export interface Report {
  project: Project;
  period: ReportPeriod;
  method: ReportMethod;
  scores: BrandScore[];
  prompts: PromptResult[];
  topSources: Source[];
  wrongFacts: WrongFact[];
  /** Past runs, oldest first, ending with this one (a single point after the first run). */
  history: HistoryPoint[];
  /** Brands named in the answers but not tracked, most named first. */
  untrackedBrands: UntrackedBrand[];
  /** ISO 8601: when the project's questions are asked again (runs are weekly); null when nothing is scheduled. */
  nextRunAt: string | null;
}

/** Narrows a report to some of the project's prompts; scores are computed over those only. */
export interface ReportFilters {
  language?: PromptLanguage;
  topic?: string;
}

// Request bodies

export type NewBrand = Omit<Brand, "id">;

export interface CreateProjectRequest {
  name: string;
  aliases: string[];
  domain: string;
  category: string;
  city: string;
  competitors: NewBrand[];
  /** Optional first question set, e.g. the questions of the free check. */
  prompts?: CreatePromptRequest[];
  /** Brand profile from onboarding; the new-project form leaves them out. */
  description?: string;
  services?: string[];
}

/** POST /projects: the new project and the run that checks its prompts for the first time. */
export interface CreateProjectResponse {
  project: Project;
  /** Poll GET /runs/{id}/progress; null when the project was created without prompts. */
  runId: string | null;
}

export type CreatePromptRequest = Pick<Prompt, "text" | "language" | "topic">;

export type UpdatePromptRequest = CreatePromptRequest;

/** Archive a question (stop asking it) or track it again. */
export interface ArchivePromptRequest {
  archived: boolean;
}

/** A question the project doesn't track yet, offered on the Questions page to accept or reject. */
export interface SuggestedPrompt {
  id: string;
  text: string;
  language: PromptLanguage;
  topic: string;
}

/** Either field or both; what's left out stays as it was. */
export interface UpdateActionRequest {
  status?: ActionStatus;
  /** Replaces the checked steps (indexes below ACTION_STEP_COUNT). */
  stepsDone?: number[];
}

export interface SendCodeRequest {
  /** E.164, e.g. "+998901234567". */
  phone: string;
}

export interface SendCodeResponse {
  /** Seconds until another code can be requested. */
  resendIn: number;
}

export interface VerifyCodeRequest {
  phone: string;
  code: string;
}

/** Fields the Telegram Login Widget returns; the backend checks `hash` with the bot token. */
export interface TelegramAuthRequest {
  id: number;
  first_name: string;
  last_name?: string;
  username?: string;
  photo_url?: string;
  auth_date: number;
  hash: string;
}

export type DemoSector = "clinic" | "real_estate" | "education" | "retail" | "other";

/** "Book a demo" form on the landing page. */
export interface DemoRequest {
  name: string;
  /** E.164, e.g. "+998901234567". */
  phone: string;
  sector: DemoSector;
}

/** A question, bug report or idea sent from the in-app help panel. */
export interface SupportMessage {
  text: string;
}

export interface SnapshotRequest {
  domain: string;
  /** Optional: when omitted, the backend works them out from the website. */
  category?: string;
  city?: string;
}

// The contract names Snapshot without fields. Assumed shape: a smaller Report
// for a brand that has no project yet (10 prompts).
export interface Snapshot {
  id: string;
  domain: string;
  category: string;
  city: string;
  method: ReportMethod;
  brand: Brand;
  competitors: Brand[];
  scores: BrandScore[];
  prompts: PromptResult[];
  topSources: Source[];
  /** What the backend found on the website; null when it couldn't be read. */
  siteChecks: SiteCheckResult[] | null;
}

// Onboarding: the backend reads the website, then suggests competitors and questions.
// Everything it returns is shown as editable, pre-filled fields.
export interface AnalyzeSiteRequest {
  domain: string;
}

/** What the backend found on the website. */
export interface SiteAnalysis {
  /** Normalized, e.g. "oqtabassum.uz". */
  domain: string;
  name: string;
  /** Other spellings it found, Latin and Cyrillic. */
  aliases: string[];
  category: string;
  city: string;
  /** A sentence or two on what the business does, written from its website. */
  description: string;
  /** What it offers, as named on the website, most important first. */
  services: string[];
}

export interface SuggestCompetitorsRequest {
  domain: string;
  name: string;
  category: string;
  city: string;
}

/** 4–6 of them, most relevant first. */
export type CompetitorSuggestion = NewBrand;

export interface SuggestPromptsRequest {
  name: string;
  category: string;
  city: string;
  /** The services the client kept; questions are suggested for them first. */
  services?: string[];
}

/** About 20 buyer questions, Uzbek and Russian, each with a topic. */
export type PromptSuggestion = CreatePromptRequest;

/** queued → running (asking ChatGPT) → analyzing (parsing answers, scores) → done; or failed. */
export type RunStatus = "queued" | "running" | "analyzing" | "done" | "failed";

/** One run asks every prompt `samples` times, so `total` = prompts × samples. */
export interface RunProgress {
  id: string;
  projectId: string;
  status: RunStatus;
  /** Answers collected so far. */
  answered: number;
  total: number;
}
